services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: inventory_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8002:8002"
        command: php artisan serve --host=0.0.0.0 --port=8002

    mysql:
        image: mysql:8.0
        container_name: inventory_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: inventory_management
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: inventory_phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "8083:80"
        depends_on:
            - mysql
